#% text_encoding = iso8859_1

:gis					Run Smallworld Core GIS
:swaf					Run CLI Smallworld Application Framework


:build_orca_swaf			Build image ORCA Swaf
:orca_swaf				ORCA Swaf
:build_orca_closed			Build image ORCA Closed
:orca_closed				ORCA Closed
:build_orca_custom_closed		Build image ORCA Custom Closed
:orca_custom_closed			ORCA Custom Closed
:build_orca_custom_sync_closed		Build image ORCA Custom Sync Closed
:orca_custom_sync_closed		ORCA Custom Sync Closed
:build_orca_custom_open			Build image ORCA Custom Open
:orca_custom_open			ORCA Custom Open
:orca_custom_open_cli			ORCA Custom Open (with CLI)
:orca_custom_open (English):		ORCA Custom Open (lang == English)
:build_orca_custom_sync_open		Build image ORCA Custom Sync Open
:orca_custom_sync_open			ORCA Custom Sync Open
:build_orca_custom_sync_dev_open	Build image ORCA Custom Sync Dev Open
:orca_custom_sync_dev_open		ORCA Custom Sync Dev Open
