
require_relative 'BuildSmallworldImage'

desc "runtime (munit)"
smallworld_image :runtime

desc "CDH dev"
smallworld_image :cdh_dev => :runtime

desc "CDH"
smallworld_image :cdh

task :default => "cdh:build"

# you can add additional output filters in this file too, eg.:
#OUTPUT_FILTERS = [
#	/MagikSF> Checking : .* for patches to rev : 4.2.0/,
#]
