require_relative 'BuildSmallworldImage'

smallworld_image :cam_db_closed_swaf, "closed cambridge"
smallworld_image :cam_db_open_swaf, "open cambridge", :cam_db_closed_swaf

task :default => "cam_db_open_swaf:build"
