SMALLWORLD_GIS: \\files3\Projects\ut\smallworld\420\utrm\Gis420\product
SW_GIS_ALIAS_FILES: <%= File.absolute_path('config\magik_images\resources\base\data\gis_aliases') %>
PROJECT_DIR: <%= Dir.pwd %>
