require_relative 'BuildSmallworldImage'

desc "all runtime software for UTRM"
smallworld_image :runtime

desc"open runtime"
smallworld_image :open =>:runtime

desc "core UTRM modules"
smallworld_image :core => :open

desc "UTRM modules"
smallworld_image :utrm =>:core

task :default => "utrm:build"
