require_relative 'Rakefile.lib'

smallworld_image :runtime, "all runtime software for UTRM"
smallworld_image :open, "open runtime", :runtime
smallworld_image :core, "core UTRM modules", :open
smallworld_image :utrm, "UTRM modules", :core

task :default => "utrm:build"
